services:
  zookeeper:
    image: debezium/zookeeper:latest
    container_name: kafka-zookeeper
    ports:
      - "2181:2181"
      - "22181:22181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - kafka-net

  kafka:
    image: debezium/kafka:latest
    container_name: kafka-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG_DIRS: 'C:\tmp\kafka\logs'
    networks:
      - kafka-net


  connect:
    image: debezium/connect:latest
    container_name: kafka-connect
    ports:
      - "8083:8083"
    environment:
      BOOTSTRAP_SERVERS: kafka:9092
      REST_PORT: 8083
      GROUP_ID: 1
      CONNECT_GROUP_ID: 'compose-connect-group'
      CONFIG_STORAGE_TOPIC: confluent_connect_configs
      OFFSET_STORAGE_TOPIC: confluent_connect_offsets
      STATUS_STORAGE_TOPIC: confluent_connect_statuses
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_INTERNAL_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_INTERNAL_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECTOR_CLIENT_CONFIG_OVERRIDE_POLICY: All
      CONNECT_REST_ADVERTISED_HOST_NAME: 'kafka-connect'
      CONNECT_PLUGIN_PATH: "/kafka/plugins,/kafka/connect"
      CLASSPATH: "/kafka/connect/ojdbc8.jar,/kafka/connect/postgresql-42.7.5.jar"
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_CONFLUENT_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_OPTS: "-Doracle.jdbc.timezoneAsRegion=false"
    depends_on:
      - zookeeper
      - kafka
    volumes:
      - C:\tmp\kafka\plugins:/kafka/plugins
      - C:\oracle\instantclient_23_6\ojdbc8.jar:/kafka/connect/ojdbc8.jar
      - C:\tmp\kafka\plugins\postgresql-42.7.5.jar:/kafka/connect/postgresql-42.7.5.jar
    networks:
      - kafka-net


  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8080:8080
    depends_on:
      - kafka
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
      KAFKA_CLUSTERS_0_NAME: wizard_test
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
    volumes:
      - C:\tmp\kafka\config.yml:/etc/kafkaui/dynamic_config.yaml
    networks:
      - kafka-net
      

  oracle:
    image: oracleinanutshell/oracle-xe-11g
    container_name: oracle-xe1
    hostname: oracle-xe1
    ports:
      - "1521:1521"
      - "5500:5500"
    environment:
      - ORACLE_PASSWORD=password
      - ORACLE_ALLOW_REMOTE="true"
    volumes:
      - C:\tmp\docker:/opt/oracle/sqldeveloper
      - C:\tmp\docker\.X11-unix:/tmp/.X11-unix
    networks:
      - kafka-net


  oracle21c:
    image: gvenzl/oracle-xe:21.3.0-full-faststart
    container_name: oracle-xe21c
    hostname: oracle-xe21c
    ports:
      - "1522:1522"
      - "5501:5501"
    environment:
      - ORACLE_PASSWORD=password
      - ORACLE_ALLOW_REMOTE="true"
    volumes:
      - C:\tmp\oracle\oraclexe21c:/opt/oracle/sqldeveloper
      - C:\tmp\oracle\oraclexe21c\init_scripts:/container-entrypoint-initdb.d 
    networks:
      - kafka-net    
      

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: microhack
    networks:
      - kafka-net


  ora2pg:
    image: georgmoser/ora2pg
    container_name: ora2pg
    privileged: true
    environment:
      - CONFIG_LOCATION=/config/myconfigfile.conf
      - OUTPUT_LOCATION=/data/myfolder
      - ORA_HOST=dbi:Oracle:host=oracle_xe1;sid=XE;port=1521
      - ORA_USER=demo_user
      - ORA_PWD=password
    volumes:
      - /config/:/config
      - /data:/data
    command: tail -f /dev/null 
    stdin_open: true
    tty: true
    networks:
      - kafka-net


  pgadmin:
    image: dpage/pgadmin4:9.0.0
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - kafka-net
    
networks:
  kafka-net:
    driver: bridge