#!/usr/bin/env bash
# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: MIT
#
# get-keys.sh
# Create the repository-root .env file from a deployed Claims MicroHack lab.

set -euo pipefail

readonly SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
readonly REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
readonly ENV_FILE="${REPO_ROOT}/.env"

resource_group=""
temporary_file=""

usage() {
  cat <<EOF
Usage: bash labautomation/get-keys.sh --resource-group <name>

Options:
  --resource-group, -g <name>  Deployed lab resource group
  --help, -h                   Show this help message
EOF
}

err() {
  printf "ERROR: %s\n" "$1" >&2
  exit 1
}

require_value() {
  local name="$1"
  local value="$2"

  if [[ -z "${value}" ]]; then
    err "Could not retrieve ${name}. Confirm the lab deployment succeeded and your account has access."
  fi
}

get_deployment_output() {
  local deployment_name="$1"
  local output_name="$2"

  if [[ -z "${deployment_name}" ]]; then
    return 0
  fi

  az deployment group show \
    --resource-group "${resource_group}" \
    --name "${deployment_name}" \
    --query "properties.outputs.${output_name}.value" \
    --output tsv
}

find_lab_deployment() {
  local deployment_name
  local project_endpoint
  local -a deployment_names

  mapfile -t deployment_names < <(
    az deployment group list \
      --resource-group "${resource_group}" \
      --query "reverse(sort_by([?properties.provisioningState=='Succeeded'], &properties.timestamp))[].name" \
      --output tsv
  )

  for deployment_name in "${deployment_names[@]}"; do
    project_endpoint=$(get_deployment_output \
      "${deployment_name}" "aiFoundryProjectEndpoint")
    if [[ -n "${project_endpoint}" ]]; then
      printf "%s" "${deployment_name}"
      return 0
    fi
  done

  return 1
}

get_resource_name() {
  local resource_type="$1"
  local name_filter="${2:-}"
  local query="[0].name"

  if [[ -n "${name_filter}" ]]; then
    query="[?contains(name, '${name_filter}')].name | [0]"
  fi

  az resource list \
    --resource-group "${resource_group}" \
    --resource-type "${resource_type}" \
    --query "${query}" \
    --output tsv
}

write_env_file() {
  local ai_foundry_project_endpoint="$1"
  local ai_foundry_endpoint="$2"
  local ai_foundry_key="$3"
  local search_endpoint="$4"
  local search_key="$5"
  local search_index_name="$6"
  local policies_container_name="$7"
  local storage_connection_string="$8"

  umask 077
  temporary_file=$(mktemp "${ENV_FILE}.tmp.XXXXXX")
  trap 'rm -f "${temporary_file}"' EXIT

  cat >"${temporary_file}" <<EOF
# Generated by labautomation/get-keys.sh. Do not commit this file.

# Microsoft Foundry project and models
AI_FOUNDRY_PROJECT_ENDPOINT=${ai_foundry_project_endpoint}
FOUNDRY_PROJECT_ENDPOINT=${ai_foundry_project_endpoint}
MODEL_DEPLOYMENT_NAME=gpt-5.4
FOUNDRY_MODEL=gpt-5.4
FOUNDRY_QUARANTINE_MODEL=gpt-5.4

# Mistral Document AI
MISTRAL_DOCUMENT_AI_ENDPOINT=${ai_foundry_endpoint}
MISTRAL_DOCUMENT_AI_KEY=${ai_foundry_key}
MISTRAL_DOCUMENT_AI_DEPLOYMENT_NAME=mistral-document-ai-2512
MISTRAL_DOCUMENT_AI_API_VERSION=2024-05-01-preview

# Azure AI Search and Foundry IQ
FOUNDRY_IQ_SEARCH_ENDPOINT=${search_endpoint}
FOUNDRY_IQ_SEARCH_KEY=${search_key}
FOUNDRY_IQ_SEARCH_INDEX_NAME=${search_index_name}
FOUNDRY_IQ_KNOWLEDGE_SOURCE_NAME=crash-statements-ks
FOUNDRY_IQ_KNOWLEDGE_BASE_NAME=crash-statements-kb
SEARCH_SERVICE_ENDPOINT=${search_endpoint}
SEARCH_ADMIN_KEY=${search_key}

# Azure Storage policy documents
AZURE_STORAGE_CONNECTION_STRING=${storage_connection_string}
AZURE_POLICIES_CONTAINER_NAME=${policies_container_name}

# Sequential workflow
HUMAN_REVIEW_CONFIDENCE_THRESHOLD=0.9
EOF

  chmod 0600 "${temporary_file}"
  mv -f "${temporary_file}" "${ENV_FILE}"
  temporary_file=""
  trap - EXIT
}

main() {
  local deployment_name
  local storage_account_name
  local policies_container_name
  local search_service_name
  local search_index_name
  local search_endpoint
  local ai_foundry_name
  local ai_foundry_project_name
  local ai_foundry_project_resource_name
  local ai_foundry_endpoint
  local ai_foundry_key
  local ai_foundry_project_endpoint
  local search_key
  local storage_connection_string

  while [[ $# -gt 0 ]]; do
    case "$1" in
      --resource-group|-g)
        if [[ -z "${2:-}" || "$2" == --* ]]; then
          err "--resource-group requires a value."
        fi
        resource_group="$2"
        shift 2
        ;;
      --help|-h)
        usage
        return 0
        ;;
      *)
        err "Unknown option: $1"
        ;;
    esac
  done

  if [[ -z "${resource_group}" ]]; then
    err "--resource-group is required."
  fi

  if ! command -v az &>/dev/null; then
    err "Azure CLI is required but was not found."
  fi

  if ! az account get-access-token --output none &>/dev/null; then
    echo "Sign in with the assigned lab account."
    az login --use-device-code
  fi

  az group show --name "${resource_group}" --output none

  echo "Locating the Claims MicroHack deployment..."
  deployment_name=$(find_lab_deployment || true)

  storage_account_name=$(get_deployment_output \
    "${deployment_name}" "storageAccountName")
  policies_container_name=$(get_deployment_output \
    "${deployment_name}" "policiesContainerName")
  search_service_name=$(get_deployment_output \
    "${deployment_name}" "searchServiceName")
  search_index_name=$(get_deployment_output \
    "${deployment_name}" "searchIndexName")
  ai_foundry_name=$(get_deployment_output \
    "${deployment_name}" "aiFoundryHubName")
  ai_foundry_project_endpoint=$(get_deployment_output \
    "${deployment_name}" "aiFoundryProjectEndpoint")

  if [[ -z "${storage_account_name}" ]]; then
    storage_account_name=$(get_resource_name \
      "Microsoft.Storage/storageAccounts")
  fi
  if [[ -z "${search_service_name}" ]]; then
    search_service_name=$(get_resource_name \
      "Microsoft.Search/searchServices")
  fi
  if [[ -z "${ai_foundry_name}" ]]; then
    ai_foundry_name=$(get_resource_name \
      "Microsoft.CognitiveServices/accounts" "aifoundry")
  fi
  if [[ -z "${policies_container_name}" ]]; then
    policies_container_name="policies"
  fi
  if [[ -z "${search_index_name}" ]]; then
    search_index_name="crash-statements"
  fi
  if [[ -z "${ai_foundry_project_endpoint}" ]]; then
    ai_foundry_project_name=$(get_deployment_output \
      "${deployment_name}" "aiFoundryProjectName")
    if [[ -z "${ai_foundry_project_name}" ]]; then
      ai_foundry_project_resource_name=$(get_resource_name \
        "Microsoft.CognitiveServices/accounts/projects")
      ai_foundry_project_name="${ai_foundry_project_resource_name#*/}"
    fi
    if [[ -z "${ai_foundry_project_name}" && \
      "${ai_foundry_name}" == *-aifoundry-* ]]; then
      ai_foundry_project_name="${ai_foundry_name/-aifoundry-/-aiproject-}"
    fi
    if [[ -n "${ai_foundry_name}" && \
      -n "${ai_foundry_project_name}" ]]; then
      ai_foundry_project_endpoint="https://${ai_foundry_name}.services.ai.azure.com/api/projects/${ai_foundry_project_name}"
    fi
  fi

  require_value "storage account name" "${storage_account_name}"
  require_value "policies container name" "${policies_container_name}"
  require_value "Search service name" "${search_service_name}"
  require_value "Search index name" "${search_index_name}"
  require_value "Foundry account name" "${ai_foundry_name}"
  require_value "Foundry project endpoint" \
    "${ai_foundry_project_endpoint}"

  search_endpoint="https://${search_service_name}.search.windows.net"
  ai_foundry_endpoint="https://${ai_foundry_name}.cognitiveservices.azure.com"

  echo "Retrieving credentials from the deployed resources..."
  storage_connection_string=$(az storage account show-connection-string \
    --resource-group "${resource_group}" \
    --name "${storage_account_name}" \
    --query connectionString \
    --output tsv)
  search_key=$(az search admin-key show \
    --resource-group "${resource_group}" \
    --service-name "${search_service_name}" \
    --query primaryKey \
    --output tsv)
  ai_foundry_key=$(az cognitiveservices account keys list \
    --resource-group "${resource_group}" \
    --name "${ai_foundry_name}" \
    --query key1 \
    --output tsv)

  require_value "storage connection string" \
    "${storage_connection_string}"
  require_value "Search admin key" "${search_key}"
  require_value "Foundry API key" "${ai_foundry_key}"

  write_env_file \
    "${ai_foundry_project_endpoint}" \
    "${ai_foundry_endpoint}" \
    "${ai_foundry_key}" \
    "${search_endpoint}" \
    "${search_key}" \
    "${search_index_name}" \
    "${policies_container_name}" \
    "${storage_connection_string}"

  echo "Created ${ENV_FILE} with permissions 600."
  if [[ -n "${deployment_name}" ]]; then
    echo "Deployment: ${deployment_name}"
  else
    echo "Deployment metadata unavailable; resources discovered from the group."
  fi
  echo "Foundry account: ${ai_foundry_name}"
  echo "Search service: ${search_service_name}"
  echo "Storage account: ${storage_account_name}"
  echo "Secret values were not displayed."
}

main "$@"
