apiVersion: batch/v1
kind: Job
metadata:
  name: adbping-performance-test
  namespace: adb-perf-test
spec:
  template:
    spec:
      containers:
      - name: adbping-tester
        image: odaamh.azurecr.io/adb-nettest:v2.1
        command: ["/bin/bash"]
        args:
        - -c
        - |
          echo "🚀 Oracle ADB Performance Test"
          echo "=============================="
          
          # Replace these placeholder values with your actual values:
          # - USER: Your Oracle ADB admin username
          # - PASSWORD: Your Oracle ADB admin password  
          # - TNS: Your complete TNS connection string from the ADB wallet
          
          USER="admin"
          PASSWORD="Welcome1234#"
          TNS="(description= (retry_count=20)(retry_delay=3)(address=(protocol=tcps)(port=1521)(host=y1jilkjp.adb.eu-paris-1.oraclecloud.com))(connect_data=(service_name=gc2401553d1c7ab_user02_high.adb.oraclecloud.com))(security=(ssl_server_dn_match=no)))"
          
          echo "📊 Starting performance test..."
          echo "Threads: 3, Duration: 30 seconds"
          echo ""
          
          adbping -u "$USER" -p "$PASSWORD" -o -l "$TNS" -c java -t 3 -d 30
          
          echo ""
          echo "✅ Performance test completed!"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      restartPolicy: Never
  backoffLimit: 3
