#cloud-config
package_update: true
packages:
  - httpd

runcmd:
  - [ sh, -c, 'echo "<html><head><title>Welcome</title></head><body><h1>Hello from RHEL on Azure!</h1></body></html>" > /var/www/html/index.html' ]
  - [ systemctl, enable, httpd.service ]
  - [ systemctl, start, httpd.service ]