#cloud-config
package_update: true
package_upgrade: true
packages:
  - httpd

runcmd:
  - systemctl start httpd.service
  - systemctl enable httpd.service
  - |
    echo "<html>
    <head>
    <title>Welcome to my site</title>
    </head>
    <body>
    <h1>Hello, World!</h1>
    <p>This is a static web page hosted on Apache on RHEL.</p>
    </body>
    </html>" > /var/www/html/index.html
  - systemctl restart httpd.service