name: Bug
description: Something is not working as expected or it is not clear what to do.
title: "[BUG] <title>"
labels: [bug, needs triage]
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the bug you encountered.
    options:
    - label: I have searched the existing issues
      required: true
- type: dropdown
  id: microhack
  attributes:
    label: Microhack
    description: Which Microhack are you reffering too?
    options:
      - 01-Identity and Access Management/1-MicroHack-ZeroTrust
      - 02-Security/1-MicroHack-Log-Analytics
      - 02-Security/2-MicroHack-Azure-Defender
      - 02-Security/3-MicroHack-Multi-Cloud-with-3rd-party
      - 02-Security/4-MicroHack-Azure-Sentinel
      - 03-Azure/01-01-App Innovation/01_AppServicetoContainerApps
      - 03-Azure/01-02 Data/01-MicroHack-SAP-Cashflow-Prediction
      - 03-Azure/01-02 Data/02-ADX-Microhack
      - 03-Azure/01-02 Data/03-SQL-Migration
      - 03-Azure/01-03-Infrastructure/01_Azure_Virtual_Desktop
      - 03-Azure/01-03-Infrastructure/02_Hybrid_Azure_Arc_Servers
      - 03-Azure/01-03-Infrastructure/03_Hybrid_Azure_Arc_Kubernetes
      - 03-Azure/01-03-Infrastructure/04_BCDR_Azure_Native
      - 03-Azure/01-03-Infrastructure/05_Azure_VMware_Solution
      - 03-Azure/01-03-Infrastructure/06_Migration_Datacenter_Modernization
      - 03-Azure/01-03-Infrastructure/07_Azure_Monitor
      - 03-Azure/01-04- AI/01_Azure_OpenAI_Service
      - 04-Microsoft-365
  validations:
    required: true
- type: textarea
  attributes:
    label: Current Behavior
    description: A concise description of what you're experiencing.
  validations:
    required: false
- type: textarea
  attributes:
    label: Expected Behavior
    description: A concise description of what you expected to happen.
  validations:
    required: false
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: Steps to reproduce the behavior.
    placeholder: |
      1. In this environment...
      1. With this config...
      1. Run '...'
      1. See error...
  validations:
    required: false
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? References? Anything that will give us more context about the issue you are encountering!

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
