name: Request a Microhack
description: You would like to see a Microhack for a topic that is not yet covered.
title: "[Request] <title>"
labels: [request, needs triage]
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the Microhack you are requesting.
    options:
    - label: I have searched the existing issues
      required: true
- type: textarea
  attributes:
    label: Microhack Description
    description: A description for the Microhack you want to be added.
  validations:
    required: true
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? References? Anything that will give us more context about the issue you are encountering!

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
