// <auto-generated />
using System;
using LegoCatalog.App.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LegoCatalog.App.Data.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    [Migration("202608180001_ContractBaseline")]
    partial class ContractBaseline
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LegoCatalog.App.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id")
                        .HasName("PK_Categories");

                    b.HasAlternateKey("Name")
                        .HasName("UQ_Categories_Name");

                    b.HasAlternateKey("Slug")
                        .HasName("UQ_Categories_Slug");

                    b.ToTable("Categories", (string)null);
                });

            modelBuilder.Entity("LegoCatalog.App.Models.LegoFigure", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1200)
                        .HasColumnType("nvarchar(1200)");

                    b.Property<string>("ImageFile")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)");

                    b.Property<DateTime>("LastUpdatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id")
                        .HasName("PK_Figures");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("IX_Figures_CategoryId");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Figures_Name");

                    b.ToTable("Figures", null, t =>
                        {
                            t.HasCheckConstraint("CK_Figures_ImageFile", "[ImageFile] = LOWER(CONVERT(varchar(36), [Id])) + '.png'");
                        });
                });

            modelBuilder.Entity("LegoCatalog.App.Models.LegoFigure", b =>
                {
                    b.HasOne("LegoCatalog.App.Models.Category", "Category")
                        .WithMany("Figures")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Figures_Categories");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("LegoCatalog.App.Models.Category", b =>
                {
                    b.Navigation("Figures");
                });
#pragma warning restore 612, 618
        }
    }
}
