-- Seed data for products
INSERT INTO products (product_id, supplier_id, name, description, price, sku, unit, img_name, discount) VALUES 
(1, 3, 'SmartFeeder One', 'This AI-powered feeder learns your cat''s snack schedule based on nap cycles and mealtime habits. It detects overeating, undernapping, and auto-updates a Feline Health Repo.', 129.99, 'CAT-FEED-001', 'piece', 'feeder.png', 0.25),
(2, 3, 'AutoClean Litter Dome', 'A self-cleaning litter box that detects patterns in your cat''s... commits. Sends you a health report and Slack alert if things look off.', 199.99, 'CAT-LITTER-001', 'piece', 'litter-box.png', 0.25),
(3, 2, 'CatFlix Entertainment Portal', 'On-demand laser shows, motion videos, and bird-watching streams - customized per cat using AI interest tracking. Think Netflix, but for felines.', 89.99, 'CAT-FLIX-001', 'piece', 'catflix.png', 0.0),
(4, 2, 'PawTrack Smart Collar', 'GPS and activity tracker with AI-powered mood detection based on tail position, purring frequency, and movement patterns. Syncs with your phone for walk stats and zoomie alerts.', 79.99, 'CAT-COLLAR-001', 'piece', 'smart-collar.png', 0.0),
(5, 1, 'WhiskerCam Pro', 'Monitor your cat''s daily shenanigans with this 360-degree camera featuring motion alerts, treat dispensing, and live streaming. Includes night vision for midnight mischief detection.', 149.99, 'CAT-CAM-001', 'piece', 'chirp-cam.png', 0.15),
(6, 1, 'ThermoNest Deluxe', 'Self-heating pet bed with temperature sensors that adjust to your cat''s preferred warmth. Includes memory foam and a built-in purr simulator for ultimate comfort.', 99.99, 'CAT-BED-001', 'piece', 'sleep-nest.png', 0.0),
(7, 1, 'ClimbCast Cat Tree', 'Multi-level climbing structure with integrated speakers, charging stations, and modular perches. Designed for modern cats who appreciate both function and style.', 299.99, 'CAT-TREE-001', 'piece', 'scratch-pad.png', 0.10),
(8, 2, 'HydroFlow Smart Bowl', 'AI-powered water fountain that monitors hydration levels and sends health alerts. Features filtration system and customizable flow patterns to entice picky drinkers.', 119.99, 'CAT-WATER-001', 'piece', 'smart-fountain.png', 0.0),
(9, 3, 'PurrFect Groomer Bot', 'Robotic grooming assistant with gentle brushes and nail trimmers. Uses AI to detect grooming preferences and stress levels for a spa-like experience.', 399.99, 'CAT-GROOM-001', 'piece', 'auto-groomer.png', 0.20),
(10, 1, 'MemoryFoam Recovery Pod', 'Therapeutic resting pod with memory foam and heat therapy for senior cats or post-surgery recovery. Includes monitoring sensors for health tracking.', 179.99, 'CAT-POD-001', 'piece', 'snack-vault.png', 0.0),
(11, 3, 'DoorDash Smart Portal', 'Smart cat door with facial recognition and time-based access. Prevents midnight squirrel parties and tracks in/out commits to your dashboard.', 159.99, 'CAT-DOOR-001', 'piece', 'door-dash.png', 0.0),
(12, 2, 'ZoomieTracker AI Mat', 'A motion-sensing mat that detects zoomies, spins up chase lights, and logs agility bursts to a weekly health report. Yes, it graphs zoomies per hour.', 79.99, 'CAT-TRACKER-001', 'piece', 'tracker-mat.png', 0.0);
