CREATE TABLE public.categories (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    name character varying(64) NOT NULL,
    slug character varying(64) NOT NULL,
    CONSTRAINT categories_pkey PRIMARY KEY (id),
    CONSTRAINT uq_categories_name UNIQUE (name),
    CONSTRAINT uq_categories_slug UNIQUE (slug)
);

CREATE TABLE public.figures (
    id uuid NOT NULL,
    name character varying(80) NOT NULL,
    description character varying(1200) NOT NULL,
    category_id bigint NOT NULL,
    image_file character varying(40) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT figures_pkey PRIMARY KEY (id),
    CONSTRAINT ck_figures_image_file CHECK ((image_file)::text = ((id)::text || '.png'::text)),
    CONSTRAINT fk_figures_categories FOREIGN KEY (category_id)
        REFERENCES public.categories (id) ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE INDEX ix_figures_category_id ON public.figures (category_id ASC);
CREATE INDEX ix_figures_name ON public.figures (name ASC);
