#!/usr/bin/env python3
"""Write the repo-root .env from deployment outputs.

By default this runs as the azd `postprovision` hook (see src/azure.yaml) and reads
the provisioned values via `azd env get-values`. Pass `--deployment <name>` to
instead read the outputs of a subscription-scoped ARM deployment (the plain-ARM
/ "Deploy to Azure" path using infra/azuredeploy.json), e.g.:

    python src/scripts/write_env.py --deployment clm-microhack

Either way it writes a .env identical in shape to the one labautomation/deploy.sh
produces, so every challenge works regardless of how you provisioned.
"""
from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
ENV_PATH = REPO_ROOT / ".env"
# azure.yaml (the azd project) lives in src/, so azd commands must run from there.
AZD_DIR = REPO_ROOT / "src"

# Keys sourced from Bicep outputs (via azd env). Fall back to the src/.env.example
# defaults for the constant-valued ones if an output is missing.
DEFAULTS = {
    "MODEL_ORCHESTRATOR": "gpt-5.4",
    "MODEL_DRAFTING": "gpt-5.4",
    "MODEL_CLAUSE_RISK": "gpt-5.6-sol",
    "MODEL_RENEWAL": "gpt-5.4-nano",
    "AZURE_SEARCH_INDEX": "clm-corpus",
    "AZURE_SEARCH_CONNECTION_NAME": "clm-search",
    "FOUNDRY_IQ_KNOWLEDGE_SOURCE": "clm-corpus-ks",
    "FOUNDRY_IQ_KNOWLEDGE_BASE": "clm-contracts-kb",
    "FOUNDRY_IQ_CONNECTION_NAME": "clm-knowledge-mcp",
    "FOUNDRY_IQ_API_VERSION": "2026-05-01-preview",
    "SHAREPOINT_DOC_LIBRARY": "Documents",
    "AZURE_TRACING_GEN_AI_CONTENT_RECORDING_ENABLED": "true",
}


def _run(cmd: list[str], cwd: Path = REPO_ROOT) -> str:
    """Run a command (default cwd = repo root), exiting with a friendly message on error."""
    try:
        proc = subprocess.run(
            cmd,
            cwd=cwd,
            capture_output=True,
            text=True,
            check=True,
        )
    except FileNotFoundError:
        sys.exit(f"✗ {cmd[0]} not found on PATH.")
    except subprocess.CalledProcessError as exc:
        sys.exit(f"✗ `{' '.join(cmd)}` failed:\n{exc.stderr}")
    return proc.stdout


def azd_env_values() -> dict[str, str]:
    """Return azd environment values as a dict (parsing KEY="value" lines)."""
    stdout = _run(["azd", "env", "get-values"], cwd=AZD_DIR)
    values: dict[str, str] = {}
    for line in stdout.splitlines():
        line = line.strip()
        if not line or "=" not in line:
            continue
        key, _, val = line.partition("=")
        values[key.strip()] = val.strip().strip('"')
    return values


def arm_env_values(deployment: str) -> dict[str, str]:
    """Return outputs of a subscription-scoped ARM deployment as a dict.

    Used for the plain-ARM / "Deploy to Azure" path (infra/azuredeploy.json),
    which has no azd environment. ARM lower-cases the first letter of output
    names, so keys are normalised to upper-case to match the .env contract.
    """
    stdout = _run([
        "az", "deployment", "sub", "show",
        "--name", deployment,
        "--query", "properties.outputs",
        "-o", "json",
    ])
    data = json.loads(stdout or "{}")
    values: dict[str, str] = {}
    for key, obj in data.items():
        val = obj.get("value", "") if isinstance(obj, dict) else obj
        values[key.upper()] = "" if val is None else str(val)
    return values


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Write the repo-root .env from deployment outputs."
    )
    parser.add_argument(
        "--deployment",
        metavar="NAME",
        help="Read values from the subscription-scoped ARM deployment of this "
             "name (the plain-ARM / Deploy-to-Azure path) instead of azd.",
    )
    args = parser.parse_args()

    env = arm_env_values(args.deployment) if args.deployment else azd_env_values()

    def get(key: str) -> str:
        return env.get(key) or DEFAULTS.get(key, "")

    content = f"""# Autogenerated by src/scripts/write_env.py — do not commit.
AZURE_AI_PROJECT_ENDPOINT={get("AZURE_AI_PROJECT_ENDPOINT")}

MODEL_ORCHESTRATOR={get("MODEL_ORCHESTRATOR")}
MODEL_DRAFTING={get("MODEL_DRAFTING")}
MODEL_CLAUSE_RISK={get("MODEL_CLAUSE_RISK")}
MODEL_RENEWAL={get("MODEL_RENEWAL")}

AZURE_SEARCH_ENDPOINT={get("AZURE_SEARCH_ENDPOINT")}
AZURE_SEARCH_INDEX={get("AZURE_SEARCH_INDEX")}
AZURE_SEARCH_CONNECTION_NAME={get("AZURE_SEARCH_CONNECTION_NAME")}
FOUNDRY_IQ_KNOWLEDGE_SOURCE={get("FOUNDRY_IQ_KNOWLEDGE_SOURCE")}
FOUNDRY_IQ_KNOWLEDGE_BASE={get("FOUNDRY_IQ_KNOWLEDGE_BASE")}
FOUNDRY_IQ_CONNECTION_NAME={get("FOUNDRY_IQ_CONNECTION_NAME")}
FOUNDRY_IQ_API_VERSION={get("FOUNDRY_IQ_API_VERSION")}

# Web grounding (Grounding with Bing Search) — populated only when Bing was
# provisioned (azd: DEPLOY_BING=true). Empty keeps web search off.
AZURE_BING_CONNECTION_NAME={get("AZURE_BING_CONNECTION_NAME")}

# SharePoint corpus (BYO) — fill these in; the AI Search SharePoint indexer in
# src/scripts/seed_corpus.py uses them. Not provisioned by Bicep (SharePoint is M365).
SHAREPOINT_SITE_URL={get("SHAREPOINT_SITE_URL")}
SHAREPOINT_DOC_LIBRARY={get("SHAREPOINT_DOC_LIBRARY")}
SHAREPOINT_APP_ID={get("SHAREPOINT_APP_ID")}
SHAREPOINT_APP_SECRET={get("SHAREPOINT_APP_SECRET")}
SHAREPOINT_TENANT_ID={get("SHAREPOINT_TENANT_ID")}

APPLICATIONINSIGHTS_CONNECTION_STRING={get("APPLICATIONINSIGHTS_CONNECTION_STRING")}
AZURE_TRACING_GEN_AI_CONTENT_RECORDING_ENABLED={get("AZURE_TRACING_GEN_AI_CONTENT_RECORDING_ENABLED")}

AZURE_SQL_CONNECTION_STRING={get("AZURE_SQL_CONNECTION_STRING")}
"""

    ENV_PATH.write_text(content, encoding="utf-8")
    print(f"✓ Wrote {ENV_PATH}")
    if not get("AZURE_AI_PROJECT_ENDPOINT"):
        print("  ! AZURE_AI_PROJECT_ENDPOINT is empty — check the deployment outputs.")
    print("  Next: python src/scripts/seed_corpus.py && python src/scripts/smoke_test.py")


if __name__ == "__main__":
    main()
