FROM mcr.microsoft.com/devcontainers/base:ubuntu

RUN curl -fsSL https://raw.githubusercontent.com/microsoft/modernize-cli/main/scripts/install.sh | \
    MODERNIZE_INSTALL_DIR=/usr/local/lib/modernize \
    MODERNIZE_BIN_DIR=/usr/local/bin \
    sh