#!/bin/bash
# Auto-generated by Terraform — opens Bastion tunnels for all workstations.
# Each tunnel forwards remote WinRM port 5986 to a unique local port.
# Run this BEFORE running the Ansible playbook.
#
# Usage: ./open-bastion-tunnels.sh
# Stop:  ./open-bastion-tunnels.sh --stop

set -e

BASTION_NAME="${bastion_name}"
BASTION_RG="${bastion_rg}"
PIDS_FILE="$(dirname "$0")/.bastion-tunnel-pids"

if [[ "$1" == "--stop" ]]; then
  echo "Stopping Bastion tunnels..."
  # Kill tracked PIDs
  if [[ -f "$PIDS_FILE" ]]; then
    while read -r pid; do
      kill "$pid" 2>/dev/null && echo "  Stopped tunnel (PID $pid)" || true
    done < "$PIDS_FILE"
    rm -f "$PIDS_FILE"
  fi
  # Also kill any orphaned bastion tunnel processes for this bastion
  pkill -f "az network bastion tunnel --name $BASTION_NAME" 2>/dev/null && echo "  Cleaned up orphaned tunnel processes" || true
  exit 0
fi

# Kill any leftover tunnels before starting new ones
pkill -f "az network bastion tunnel --name $BASTION_NAME" 2>/dev/null || true
sleep 1

echo "Opening Bastion tunnels (Bastion: $BASTION_NAME in $BASTION_RG)..."
echo ""

> "$PIDS_FILE"

%{ for i, idx in indices ~}
echo "  workstation-${format("%02d", idx)}: localhost:${55986 + i} -> ${workstation_ips[i]}:5986"
az network bastion tunnel \
    --name "$BASTION_NAME" \
    --resource-group "$BASTION_RG" \
    --target-resource-id "${workstation_vm_ids[i]}" \
    --resource-port 5986 \
    --port ${55986 + i} &
echo $! >> "$PIDS_FILE"

%{ endfor ~}

echo ""
echo "All tunnels started. Waiting for tunnels to establish..."
sleep 10
echo "Ready. Run the Ansible playbook now:"
echo "  ansible-playbook -i inventory.yml playbook-workstation.yml --extra-vars \"ansible_password=<password>\""
echo ""
echo "To stop tunnels later: $0 --stop"
