// CPU-only local AI recipe for the MicroHack's default K3s VM.

@description('Information about the resource consuming this Recipe. Generated by Radius.')
param context object

@description('Ollama model tag. Keep the default for the 4-vCPU, 16-GiB workshop VM.')
param model string = context.resource.properties.?model ?? 'qwen2.5:0.5b'

@description('Pinned multi-architecture Ollama image.')
param ollamaImage string = 'ollama/ollama:0.11.10@sha256:a5409cb903d30f9cd67e9f430dd336ddc9274e16fd78f75b675c42065991b4fd'

var workloadName = 'ollama-${uniqueString(context.resource.id)}'
var namespace = context.runtime.kubernetes.namespace

extension kubernetes with {
  kubeConfig: ''
  namespace: namespace
} as kubernetes

resource ollama 'apps/Deployment@v1' = {
  metadata: {
    name: workloadName
    namespace: namespace
    labels: {
      app: workloadName
      resource: context.resource.name
      'radapp.io/application': context.application == null ? '' : context.application.name
    }
  }
  spec: {
    replicas: 1
    strategy: {
      type: 'Recreate'
    }
    selector: {
      matchLabels: {
        app: workloadName
      }
    }
    template: {
      metadata: {
        labels: {
          app: workloadName
          resource: context.resource.name
          'radapp.io/application': context.application == null ? '' : context.application.name
        }
      }
      spec: {
        terminationGracePeriodSeconds: 30
        containers: [
          {
            name: 'ollama'
            image: ollamaImage
            imagePullPolicy: 'IfNotPresent'
            command: [
              '/bin/sh'
              '-c'
            ]
            args: [
              '''set -eu
ollama serve &
server_pid=$!
until ollama list >/dev/null 2>&1; do
  sleep 2
done
ollama pull "$OLLAMA_MODEL"
wait "$server_pid"
'''
            ]
            env: [
              {
                name: 'OLLAMA_HOST'
                value: '0.0.0.0:11434'
              }
              {
                name: 'OLLAMA_MODELS'
                value: '/models'
              }
              {
                name: 'OLLAMA_KEEP_ALIVE'
                value: '-1'
              }
              {
                name: 'OLLAMA_MODEL'
                value: model
              }
            ]
            ports: [
              {
                name: 'http'
                containerPort: 11434
              }
            ]
            resources: {
              requests: {
                cpu: '500m'
                memory: '2Gi'
              }
              limits: {
                cpu: '4'
                memory: '8Gi'
              }
            }
            startupProbe: {
              exec: {
                command: [
                  'ollama'
                  'show'
                  model
                ]
              }
              periodSeconds: 10
              failureThreshold: 60
            }
            readinessProbe: {
              httpGet: {
                path: '/api/tags'
                port: 11434
              }
              periodSeconds: 10
              failureThreshold: 6
            }
            livenessProbe: {
              httpGet: {
                path: '/api/tags'
                port: 11434
              }
              initialDelaySeconds: 30
              periodSeconds: 30
              failureThreshold: 3
            }
            securityContext: {
              allowPrivilegeEscalation: false
              capabilities: {
                drop: [
                  'ALL'
                ]
              }
            }
            volumeMounts: [
              {
                name: 'models'
                mountPath: '/models'
              }
            ]
          }
        ]
        volumes: [
          {
            name: 'models'
            emptyDir: {}
          }
        ]
      }
    }
  }
}

resource ollamaService 'core/Service@v1' = {
  metadata: {
    name: workloadName
    namespace: namespace
    labels: {
      app: workloadName
    }
  }
  spec: {
    type: 'ClusterIP'
    selector: {
      app: workloadName
    }
    ports: [
      {
        name: 'http'
        port: 11434
        targetPort: 11434
      }
    ]
  }
}

output result object = {
  resources: [
    '/planes/kubernetes/local/namespaces/${namespace}/providers/apps/Deployment/${ollama.metadata.name}'
    '/planes/kubernetes/local/namespaces/${namespace}/providers/core/Service/${ollamaService.metadata.name}'
  ]
  values: {
    provider: 'local'
    endpoint: 'http://${ollamaService.metadata.name}.${namespace}.svc.cluster.local:11434/v1'
    model: model
    secrets: {
      #disable-next-line outputs-should-not-contain-secrets
      apiKey: ''
    }
  }
}
