// Reference recipe for a pre-provisioned Azure OpenAI deployment.

@description('Information about the resource consuming this Recipe. Generated by Radius.')
param context object

@description('Azure OpenAI account endpoint reachable from the target cluster.')
@minLength(1)
param endpoint string

@description('Existing Azure OpenAI deployment name.')
@minLength(1)
param deploymentName string

output result object = {
  resources: []
  values: {
    provider: 'azure'
    endpoint: endpoint
    model: deploymentName
    secrets: {
      #disable-next-line outputs-should-not-contain-secrets
      apiKey: ''
    }
  }
}
