apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        version: v1
    spec:
      containers:
      - name: frontend
        image: acrakslabmwms.azurecr.io/sample-app/frontend:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: BACKEND_URL
          value: "http://backend:3001"