---
- block:

  - name: copy demo_schema check script
    when: inventory_hostname in groups['ora-x1']
    template: src=checkdata.sql.j2 dest=/tmp/checkdata.sql
    become_user: "{{ oracle_user }}"
 
#    #TODO: https://vjdba.wordpress.com/tag/rman-05537/
#  
  - name: check if sample data exist in the demo_schema in database
    when: inventory_hostname in groups['ora-x1']
    become_user: "{{ oracle_user }}"
    shell: echo @"/tmp/checkdata.sql;" | sqlplus / as sysdba
    register: sql_output

  - debug: var=sql_output.stdout_lines
  become: true
  become_user: "{{ oracle_user }}"

- name: Extract numeric count from SQL output
  when: inventory_hostname in groups['ora-x1']
  set_fact:
    count_result: "{{ sql_output.stdout_lines | select('match', '^\\s*\\d+\\s*$') | list | first | trim }}"


- name: Debug the count result
  debug:
    msg: "The count is: {{ count_result }}"

- name: Ensure schema data state is as expected
  when: inventory_hostname in groups['ora-x1']
  assert:
    that:
      - "( count_result | int) > 3"
    success_msg: "Result of 'SELECT COUNT(*) FROM demo_schema.EMPLOYEES;' is {{ count_result }}"
    fail_msg: "The SQL query did not return a count lesser than 3"

- block:

  - name: copy single instance check script
    when: inventory_hostname in groups['ora-x1']
    template: src=sicheck.sql.j2 dest=/tmp/sicheck.sql
    become_user: "{{ oracle_user }}"
 
#    #TODO: https://vjdba.wordpress.com/tag/rman-05537/
#  
  - name: check primary database state
    when: inventory_hostname in groups['ora-x1']
    become_user: "{{ oracle_user }}"
    shell: echo @"/tmp/sicheck.sql;" | sqlplus / as sysdba
    register: sql_output

  - debug: var=sql_output.stdout_lines
  become: true
  become_user: "{{ oracle_user }}"

- name: Ensure database state is as expected
  when: inventory_hostname in groups['ora-x1']
  assert:
    that:
      - "'OPEN' in sql_output.stdout"
      - "'ACTIVE' in sql_output.stdout"
    success_msg: "The database is up and running"
    fail_msg: "The SQL query did not return the expected output"